name: arielapp
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http:
  rxdart:
  shared_preferences:
  url_launcher:
  flutter_calendar_carousel:
  

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.0

flutter_icons:
  android: true 
  ios: true
  image_path: "assets/icon/icon.png"
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/images/logo.png
    - assets/images/logo-white.png
    - assets/images/icono-contacto.png
    - assets/images/contacto.png
    - assets/images/datos-personales.png
    - assets/images/gestiones.png
    - assets/images/inicio.png
    - assets/images/noticias.png
    - assets/images/propiedades.png
    - assets/images/aeronaves.png
    - assets/images/arrow.png
    - assets/images/back-arrow.png
    - assets/images/action-arrow.png
    - assets/images/arrow-down.png
    - assets/images/reservar-white.png
    - assets/images/bullet.png
    - assets/images/calendar.png
    - assets/images/beds.png
    - assets/images/bell.png
    - assets/images/reception.png
    - assets/images/building.png
    - assets/images/location.png
    - assets/images/maintenance.png
    - assets/images/parking.png
    - assets/images/wifi.png
    - assets/images/reservar.png
    - assets/images/icon-menu.png
    - assets/images/water-mark.png
    - assets/images/antigua.png
    - assets/images/riodulce.png
    - assets/images/miami.png
    - assets/images/houston.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  fonts:
    - family: DomaineText
      fonts:
        - asset: assets/fonts/DomaineText-Black.otf
        - asset: assets/fonts/DomaineText-Bold.otf
        - asset: assets/fonts/DomaineText-Light.otf
        - asset: assets/fonts/DomaineText-Medium.otf
        - asset: assets/fonts/DomaineText-Regular.otf
          style: italic
        - asset: assets/fonts/DomaineText-BlackItalic.otf
        - asset: assets/fonts/DomaineText-BoldItalic.otf
        - asset: assets/fonts/DomaineText-LightItalic.otf
        - asset: assets/fonts/DomaineText-MediumItalic.otf
        - asset: assets/fonts/DomaineText-RegularItalic.otf
    - family: Revisal
      fonts:
        - asset: assets/fonts/Revisal.otf
        - asset: assets/fonts/RevisalBlack.otf
        - asset: assets/fonts/RevisalBlackItalic.otf
        - asset: assets/fonts/RevisalHairline.otf
        - asset: assets/fonts/RevisalHairlineItalic.otf
        - asset: assets/fonts/RevisalLight.otf
        - asset: assets/fonts/RevisalLightItalic.otf
        - asset: assets/fonts/RevisalMedium.otf
        - asset: assets/fonts/RevisalMediumItalic.otf
        - asset: assets/fonts/RevisalRegularItalic.otf
        - asset: assets/fonts/RevisalThin.otf
        - asset: assets/fonts/RevisalThinItalic.otf
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
